USE EMPLOYEE;

DESC DEPARTMENT;

-- Adding LOCATION COLUMN to department table --
ALTER TABLE DEPARTMENT
ADD COLUMN LOCATION VARCHAR(255);
SELECT * FROM DEPARTMENT;

-- ADDING LOACTION VALUES --
UPDATE DEPARTMENT
-- SET LOCATION = 'NEW YORK' WHERE DEPTNO = 10;
-- SET LOCATION = 'CHICAGO' WHERE DEPTNO = 20;
-- SET LOCATION = 'SWEDEN' WHERE DEPTNO = 30;
SET LOCATION = 'JAPAN' WHERE DEPTNO = 40; 

SELECT * FROM DEPARTMENT;