SHOW DATABASES;

-- CREATING DATABASE --
CREATE DATABASE employee;
SHOW DATABASES;

-- USING THE DATABASE CREATED --
USE employee;

-- CREATE TABLE DEPARTMENT --
CREATE TABLE department(
deptno INT PRIMARY KEY, 
dname VARCHAR(255));

SHOW TABLES;