USE EMPLOYEE;

-- Experiment 7 (JOINS CONCEPT) --
-- Q1. Display all employees with their dept name --
SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL,
E.DEPTNO, D.DNAME
FROM EMPLOYEE E INNER JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO;

-- Q2. Display those employees whose manager names is jones, and also display their manager name --
SELECT E.ENAME AS EMPLOYEE_NAME,
MG.ENAME AS MANAGER_NAME
FROM EMPLOYEE E JOIN EMPLOYEE MG
ON E.MGR = MG.EMPNO
WHERE MG.ENAME = 'JONES';

-- Q3. Display employee name, his job, his dept name, his manager name, his grade and make out of an under department wise --
SELECT E.ENAME AS EMPLOYEE_NAME, E.JOB AS EMPLOYEE_JOB, 
D.DNAME AS DEPARTMENT_NAME, 
MG.ENAME AS MANAGER_NAME, 
SG.GRADE AS GRADE_PAY
FROM EMPLOYEE E 
INNER JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO   /* DEPT */
JOIN  EMPLOYEE MG ON E.MGR = MG.EMPNO   /* MANAGER NAME */
JOIN SALGRADE SG ON E.SAL BETWEEN MINPAY AND MAXPAY
ORDER BY D.DNAME;

-- Q4. List out all the employees name, job, and salary grade and department name for everyone in the company except 'clerk'. Sort on salary display the highest salary --
SELECT E.ENAME AS EMPLOYEE_NAME, E.JOB AS EMPLOYEE_JOB, 
SG.GRADE AS GRADE_PAY, D.DNAME AS DEPARTMENT_NAME
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO 
JOIN SALGRADE SG ON E.SAL BETWEEN MINPAY AND MAXPAY
WHERE E.JOB <> 'CLERK'
ORDER BY E.SAL DESC;

-- Q5. Display employee name, his job and his manager. Display also employees who are without manager --
SELECT E.ENAME AS EMPLOYEE_NAME, E.JOB AS EMPLOYEE_JOB, 
IFNULL(MG.ENAME, 'NO MANAGER') AS MANAGER_NAME
FROM EMPLOYEE E 
LEFT JOIN EMPLOYEE MG ON E.MGR = MG.EMPNO;

-- Q6. List the employee name, job, annual salary, deptno, dept name and grade who earn 36000 a year or who are not clerks --
SELECT E.ENAME AS EMPLOYEE, E.JOB AS EMPLOYEE_JOB, 
(E.SAL * 12) AS ANNUAL_SAL, E.DEPTNO AS DEPARTMENT_NUMBER, 
D.DNAME AS DEPARTMENT_NAME, SG.GRADE AS GRADE_PAY
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
INNER JOIN SALGRADE SG ON E.SAL BETWEEN MINPAY AND MAXPAY
WHERE (E.SAL * 12) = 36000 OR E.JOB <> 'CLERK';

-- Q7. List ename, job, annual sal, deptno, dname and grade who earn 30000 per year and who are not clerks --
SELECT E.ENAME AS EMPLOYEE_NAME, E.JOB AS EMPLOYEE_JOB,
(E.SAL * 12) AS ANNUAL_SAL, E.DEPTNO AS DEPARTMENT_NUMBER,
D.DNAME AS DEPARTMENT_NAME, SG.GRADE AS GRADE_PAY
FROM EMPLOYEE E 
INNER JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
INNER JOIN SALGRADE SG ON E.SAL BETWEEN MINPAY AND MAXPAY
WHERE (E.SAL * 12) = 30000 AND E.JOB <> 'CLERK';

-- Q8. List out all employees by name and number along with their manager's name and number also display 'no manager' who has no manager --
SELECT E.EMPNO AS EMPLOYEE_NUMBER, E.ENAME AS EMPLOYEE_NAME,
IFNULL(M.EMPNO, '-') AS MANAGER_EMPNO,
IFNULL(M.ENAME, 'NO MANAGER') AS MANAGER_NAME
FROM EMPLOYEE E 
LEFT JOIN EMPLOYEE M ON E.MGR = M.EMPNO;

-- Q9. Select dept name, dept no and sum of sal --
SELECT D.DEPTNO AS DEPARTMENT_NUMBER, D.DNAME AS DEPARTMENT_NAME,
SUM(E.SAL) AS TOTAL_SALARY
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
GROUP BY D.DNAME, D.DEPTNO;

-- Q10. Display employee number, name and location of the department in which he is working --
SELECT E.EMPNO AS EMPLOYEE_NUMBER, E.ENAME AS EMPLOYEE_NAME,
D.LOCATION AS POSTING_PLACE
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO;

-- Q11. Display employee name and department name for each employee -- 
SELECT E.ENAME AS EMPLOYEE_NAME, D.DNAME AS DEPARTMENT_NAME
FROM EMPLOYEE E INNER JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO;
